'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { useApp } from '../../context/AppContext';
import {
  Sparkles,
  ShieldCheck,
  Clock,
  IndianRupee,
  Layers,
  ArrowRight,
  GitFork,
  FileCheck,
  CheckCircle2,
  AlertTriangle,
  Info,
  Building2,
  ExternalLink
} from 'lucide-react';

export default function DiscoveryPage() {
  const { approvals, project, business } = useApp();
  const [filterType, setFilterType] = useState<'all' | 'mandatory' | 'conditional'>('all');

  const filteredApprovals = approvals.filter(app => {
    if (filterType === 'mandatory') return app.type === 'mandatory';
    if (filterType === 'conditional') return app.type === 'conditional';
    return true;
  });

  const totalFee = approvals.reduce((sum, a) => sum + a.fee, 0);

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-8">
      
      {/* Top Header & Breadcrumb */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-200 pb-6">
        <div>
          <div className="flex items-center space-x-2 text-xs font-semibold text-sarthi-600 mb-1">
            <Sparkles className="w-4 h-4 text-amber-500" />
            <span>AI Regulatory Inference Engine</span>
            <span>•</span>
            <span className="text-slate-500 font-mono">Profile ID: {project.id}</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight">
            AI Approval Discovery & Compliance Blueprint
          </h1>
          <p className="text-xs sm:text-sm text-slate-600 mt-1">
            Synthesized statutory clearances for{' '}
            <strong className="text-slate-900">{project.name}</strong> ({project.sector}) with ₹{project.proposedInvestmentCr} Cr Capex.
          </p>
        </div>

        {/* Quick Nav CTAs */}
        <div className="flex items-center space-x-2.5">
          <Link
            href="/dependency-graph"
            className="flex items-center space-x-2 px-4 py-2.5 rounded-xl bg-sarthi-600 hover:bg-sarthi-700 text-white text-xs font-bold shadow-md transition"
          >
            <GitFork className="w-4 h-4" />
            <span>Interactive Dependency Graph</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </Link>
          <Link
            href="/documents"
            className="flex items-center space-x-2 px-4 py-2.5 rounded-xl bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 text-xs font-bold transition"
          >
            <FileCheck className="w-4 h-4 text-sarthi-600" />
            <span>Document Checklist</span>
          </Link>
        </div>
      </div>

      {/* Prominent Statutory Disclaimer Banner */}
      <div className="p-4 rounded-2xl bg-amber-50/90 border-2 border-amber-300 text-amber-950 flex items-start space-x-3 shadow-xs">
        <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
        <div className="text-xs leading-relaxed">
          <strong className="font-bold uppercase tracking-wider text-amber-900 block mb-0.5">
            Statutory AI Guidance Disclaimer
          </strong>
          This clearance discovery is generated by an algorithmic rules engine analyzing your industrial inputs.
          Requirements, prescribed fees, and scrutiny steps{' '}
          <strong className="underline decoration-amber-500">must be verified with the concerned statutory authorities</strong>.
          This output serves as decision support and does not constitute a legally binding approval order.
        </div>
      </div>

      {/* Summary KPI Ribbon */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-2xs">
          <div className="text-xs text-slate-500 font-semibold uppercase">Total Approvals</div>
          <div className="text-2xl font-black text-slate-900 mt-1">{approvals.length} Clearances</div>
          <div className="text-[11px] text-emerald-600 font-medium mt-0.5">7 Mandatory, 1 Conditional</div>
        </div>
        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-2xs">
          <div className="text-xs text-slate-500 font-semibold uppercase">Departments Involved</div>
          <div className="text-2xl font-black text-sarthi-700 mt-1">6 State Agencies</div>
          <div className="text-[11px] text-slate-500 mt-0.5">MIDC, MPCB, DISH, MFS, MSEDCL</div>
        </div>
        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-2xs">
          <div className="text-xs text-slate-500 font-semibold uppercase">Est. Cumulative Fees</div>
          <div className="text-2xl font-black text-slate-900 mt-1">₹{(totalFee / 1000).toFixed(0)},000</div>
          <div className="text-[11px] text-slate-500 mt-0.5">Consolidated single-window payment</div>
        </div>
        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-2xs">
          <div className="text-xs text-slate-500 font-semibold uppercase">Overall AI Confidence</div>
          <div className="text-2xl font-black text-emerald-600 mt-1">96.5%</div>
          <div className="text-[11px] text-emerald-700 font-medium mt-0.5">High Concordance with DCR 2024</div>
        </div>
      </div>

      {/* Filter Tabs */}
      <div className="flex items-center space-x-2 border-b border-slate-200 pb-2">
        <button
          onClick={() => setFilterType('all')}
          className={`px-3 py-1.5 rounded-lg text-xs font-bold transition ${
            filterType === 'all'
              ? 'bg-sarthi-600 text-white shadow-2xs'
              : 'text-slate-600 hover:bg-slate-100'
          }`}
        >
          All Required Clearances ({approvals.length})
        </button>
        <button
          onClick={() => setFilterType('mandatory')}
          className={`px-3 py-1.5 rounded-lg text-xs font-bold transition ${
            filterType === 'mandatory'
              ? 'bg-sarthi-600 text-white shadow-2xs'
              : 'text-slate-600 hover:bg-slate-100'
          }`}
        >
          Mandatory Only ({approvals.filter(a => a.type === 'mandatory').length})
        </button>
        <button
          onClick={() => setFilterType('conditional')}
          className={`px-3 py-1.5 rounded-lg text-xs font-bold transition ${
            filterType === 'conditional'
              ? 'bg-sarthi-600 text-white shadow-2xs'
              : 'text-slate-600 hover:bg-slate-100'
          }`}
        >
          Conditional ({approvals.filter(a => a.type === 'conditional').length})
        </button>
      </div>

      {/* Approvals Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {filteredApprovals.map((app, idx) => (
          <div
            key={app.id}
            className="bg-white rounded-2xl border border-slate-200 p-5 shadow-xs hover:shadow-md transition space-y-4 flex flex-col justify-between"
          >
            <div>
              {/* Card Header */}
              <div className="flex items-start justify-between gap-2 mb-2">
                <div className="flex items-center gap-2">
                  <span className="text-xs font-mono font-bold px-2 py-0.5 rounded bg-slate-100 text-slate-700 border border-slate-200">
                    {app.code}
                  </span>
                  <span
                    className={`text-[10px] uppercase font-bold px-2 py-0.5 rounded-full ${
                      app.type === 'mandatory'
                        ? 'bg-rose-50 text-rose-700 border border-rose-200'
                        : 'bg-amber-50 text-amber-700 border border-amber-200'
                    }`}
                  >
                    {app.type}
                  </span>
                </div>
                <div className="flex items-center space-x-1 text-xs font-mono font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-md border border-emerald-200">
                  <Sparkles className="w-3 h-3 text-emerald-600" />
                  <span>{app.confidenceScore}% AI Confidence</span>
                </div>
              </div>

              {/* Title & Department */}
              <h3 className="text-base font-bold text-slate-900 leading-snug">{app.name}</h3>
              <p className="text-xs text-sarthi-700 font-medium mt-0.5">{app.department}</p>

              {/* AI Reasoning Pill */}
              <div className="mt-3 p-3 rounded-xl bg-slate-50 border border-slate-200 text-xs text-slate-700 leading-relaxed">
                <strong className="text-slate-900 font-semibold block mb-1">
                  Why this approval is triggered:
                </strong>
                {app.reason}
              </div>

              {/* Required Documents List */}
              <div className="mt-3 space-y-1">
                <div className="text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                  Mandatory Documents ({app.requiredDocuments.length})
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {app.requiredDocuments.map((doc, dIdx) => (
                    <span
                      key={dIdx}
                      className="text-[11px] px-2 py-0.5 rounded bg-slate-100 text-slate-700 border border-slate-200 truncate max-w-[200px]"
                      title={doc}
                    >
                      {doc}
                    </span>
                  ))}
                </div>
              </div>
            </div>

            {/* Bottom Meta & Action */}
            <div className="pt-3 border-t border-slate-100 flex items-center justify-between">
              <div className="space-y-0.5 text-xs">
                <div className="text-slate-500 flex items-center gap-1 font-mono">
                  <Clock className="w-3.5 h-3.5 text-slate-400" />
                  <span>SLA: {app.timelineDays} Days</span>
                </div>
                <div className="text-slate-800 font-semibold font-mono">
                  Fee: ₹{app.fee.toLocaleString('en-IN')}
                </div>
              </div>

              <div className="flex items-center space-x-2">
                <Link
                  href={
                    app.applicationId
                      ? `/applications/${app.applicationId}`
                      : '/documents'
                  }
                  className="px-3.5 py-1.5 rounded-lg bg-sarthi-50 hover:bg-sarthi-100 text-sarthi-700 text-xs font-bold border border-sarthi-200 transition"
                >
                  {app.status === 'COMPLETED' ? 'View Sanction' : 'Track / Apply'}
                </Link>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Next Step Action Banner */}
      <div className="p-6 rounded-2xl bg-gradient-to-r from-slate-900 to-sarthi-950 text-white flex flex-col sm:flex-row items-center justify-between gap-4">
        <div>
          <h4 className="text-base font-bold">Ready to map prerequisites & downstream dependencies?</h4>
          <p className="text-xs text-slate-400 mt-0.5">
            Visualize the exact DAG execution path to see which approvals can run in parallel.
          </p>
        </div>
        <Link
          href="/dependency-graph"
          className="flex items-center space-x-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-sarthi-500 to-blue-600 hover:from-sarthi-400 hover:to-blue-500 text-white text-xs font-bold transition shadow-md shrink-0"
        >
          <span>Open Dependency Graph</span>
          <ArrowRight className="w-4 h-4" />
        </Link>
      </div>

    </div>
  );
}
